#!/usr/bin/env python3
"""Generate si-xr.tex from si.aux for cross-document refs under Tectonic.

Tectonic's bundle does not expose si.aux to main.tex when compiling separately,
so \\externaldocument fails. This script mirrors xr-hyper's label import as a
plain .tex file that Tectonic can \\input.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

PREFIX = "si-"
AUX_NAME = "si.aux"
OUT_NAME = "si-xr.tex"

_S_PREFIX = re.compile(r"^\{S(\d+(?:\.\d+)?)\}")


def read_braced(text: str, start: int) -> tuple[str, int]:
    """Read one {...} group; start must point at '{'. Returns (inner, pos_after)."""
    if start >= len(text) or text[start] != "{":
        raise ValueError(f"expected '{{' at {start}")
    depth = 0
    i = start
    while i < len(text):
        ch = text[i]
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                return text[start + 1 : i], i + 1
        elif ch == "\\" and i + 1 < len(text):
            i += 1
        i += 1
    raise ValueError("unbalanced braces in aux file")


def parse_newlabels(aux_text: str) -> dict[str, str]:
    labels: dict[str, str] = {}
    needle = "\\newlabel{"
    pos = 0
    while True:
        idx = aux_text.find(needle, pos)
        if idx == -1:
            break
        key_brace = idx + len(needle) - 1
        key, cursor = read_braced(aux_text, key_brace)
        value, cursor = read_braced(aux_text, cursor)
        labels[key] = value
        pos = cursor
    return labels


def strip_section_s_prefix(value: str) -> str:
    """RevTeX may emit S1/S5.2; main text uses 'Supplementary Section 1'."""
    return _S_PREFIX.sub(r"{\1}", value, count=1)


def generate_xr_tex(labels: dict[str, str], prefix: str = PREFIX) -> str:
    lines = [
        "% Auto-generated by gen-si-xr.py — do not edit by hand.",
        "% Regenerate after compiling si.tex: python3 gen-si-xr.py",
        "\\makeatletter",
    ]
    skip = {"FirstPage", "LastPage"}
    for key in sorted(labels.keys()):
        if key in skip:
            continue
        value = labels[key]
        # keep the S-prefixed form (e.g. S17) so main-text references read
        # "Supplementary Note S17", matching the SI's own headings
        csname = f"r@{prefix}{key}".replace("#", "\\#")
        lines.append(f"\\expandafter\\gdef\\csname {csname}\\endcsname{{{value}}}")
    lines.append("\\makeatother")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    article_dir = Path(__file__).resolve().parent
    aux_path = article_dir / AUX_NAME
    out_path = article_dir / OUT_NAME

    if not aux_path.is_file():
        print(f"error: {aux_path} not found — compile si.tex first", file=sys.stderr)
        return 1

    aux_text = aux_path.read_text(encoding="utf-8", errors="replace")
    labels = parse_newlabels(aux_text)
    if not labels:
        print(f"error: no \\newlabel entries in {aux_path}", file=sys.stderr)
        return 1

    out_path.write_text(generate_xr_tex(labels), encoding="utf-8")
    print(f"wrote {out_path.name} ({len(labels)} labels from {AUX_NAME})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
