#!/usr/bin/env python3
"""The paper's main figures -- this script produces Fig 1/2/4/5, in Arial, as multi-panel
layouts. All data is read from paper/data/*.csv.

Figure order (the discovery-led narrative line):
  Fig 1  how the laws were discovered: the agentic law learning loop, its scale, the
         refutation ledger, the evidence store
  Fig 2  the discovered laws themselves: every law and formula shown at once, their joint
         performance, and a head-to-head comparison with Pauling
  Fig 3  validation, blind spots and guards -- moved out of this script and generated by
         src/fig3_detection.py
         (the cross-database comparison panel is panel d of the legacy asset figS10, shown in
         the main text as Supplementary Fig. S2d; see src/si_figs.py)
  Fig 4  what the laws replace: Pauling's rules fail mainly by "abstaining" rather than by
         getting things wrong
  Fig 5  the full refutation ledger

Naming (matching the main text):
  ALL         agentic law learning
  rho         reduced contact ratio, min_bonds d/(r_cat + r_an)
  Born floor  the lower-bound law on rho (D1)
  commitment profile   (commitment rate, accuracy when committed)

Panel-letter alignment: always through stamp(), clustered by gridspec row and column; panels
in one column share an x and panels in one row share a y, with x taken at the leftmost edge
of every y-axis decoration in that column (tick labels + axis title).
"""
from __future__ import annotations
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.patches as mp
from matplotlib.colors import to_rgba
import numpy as np, pandas as pd, pathlib, json

ROOT = pathlib.Path(__file__).resolve().parent.parent
D = pathlib.Path(__file__).resolve().parent.parent / "paper"
DATA, OUT = D / "data", D / "figs"
SI_DATA = D / "si_data"
OUT.mkdir(parents=True, exist_ok=True)

plt.rcParams.update({
    "font.family": "Arial", "font.sans-serif": ["Arial", "Liberation Sans"],
    "font.size": 8.5, "axes.labelsize": 9, "axes.titlesize": 9,
    "xtick.labelsize": 8, "ytick.labelsize": 8, "legend.fontsize": 8,
    "axes.linewidth": 0.6, "xtick.major.width": 0.6, "ytick.major.width": 0.6,
    "xtick.major.size": 2.5, "ytick.major.size": 2.5,
    "axes.spines.top": False, "axes.spines.right": False,
    "figure.dpi": 400, "savefig.dpi": 400, "savefig.bbox": "tight",
    "savefig.pad_inches": 0.02, "pdf.fonttype": 42, "ps.fonttype": 42,
    "svg.fonttype": "none",
    "mathtext.fontset": "custom", "mathtext.rm": "Arial",
    "mathtext.it": "Arial:italic", "mathtext.bf": "Arial:bold",
})

import figure_palette  # noqa: F401  (registers the ramps, caps bar opacity)

CM = 1 / 2.54
W1, W2 = 8.9 * CM, 18.3 * CM                      # Nature single / double column
BLU, RED, ORA, GRN, GRY, PUR = ("#005B93", "#D6564C", "#9861B0",
                                "#156646", "#8A8C8E", "#35A7D8")
SETC = {"L1": BLU, "L1'": PUR, "L2": ORA, "L3": RED, "L4": "#0A5A3C"}
BAR_FACE_ALPHA = 0.38
BAR_EDGE_WIDTH = 0.85


def style_bar_container(
    bars,
    colours,
    *,
    face_alpha: float = BAR_FACE_ALPHA,
    edge_width: float = BAR_EDGE_WIDTH,
    opaque_fill_weight: float | None = None,
):
    """Give bars a same-hue outline and either translucent or pale opaque fill."""
    if isinstance(colours, str):
        colours = [colours] * len(bars)
    if len(colours) != len(bars):
        raise ValueError("one bar colour is required for every patch")
    for bar, colour in zip(bars, colours, strict=True):
        # figure_palette applies an artist-level opacity cap to every bar call.
        # Clear it so the face and outline can have independent alpha values.
        if opaque_fill_weight is None:
            bar.set_alpha(None)
            bar.set_facecolor(to_rgba(colour, face_alpha))
        else:
            if not 0.0 <= opaque_fill_weight <= 1.0:
                raise ValueError("opaque_fill_weight must lie in [0, 1]")
            base = np.asarray(to_rgba(colour)[:3])
            face = opaque_fill_weight * base + (1.0 - opaque_fill_weight)
            bar.set_alpha(1.0)
            bar.set_facecolor((*face, 1.0))
        bar.set_edgecolor(to_rgba(colour, 1.0))
        bar.set_linewidth(edge_width)
    return bars


def setlab(key, prime="′"):
    """Archive key of a law set -> its display name in the figure (Set 1--Set 4, matching the
    main text).

    The archived result tables are still keyed on L1/L1'/L2/L3/L4, so key and display name are
    kept apart: the conversion happens only at draw time and every data index uses the
    original key.
    """
    return "Set " + key[1:].replace("'", prime)


def dmglab(key):
    """Archive key of a damage class -> its display name in the figure (S1--S5 -> D1--D5).

    The archived tables and the kind column are still keyed on S1--S5; the renaming happens
    only at draw time, since otherwise it would be misread as the main text's Set 1--Set 5.
    """
    return "D" + key[1:]


# ─────────────────────────────────────────────────────────────────────────────
# panel letters: grid alignment
# ─────────────────────────────────────────────────────────────────────────────
def _ydeco_left(ax, fig, rend):
    """The leftmost edge of every y-axis decoration to the left of this axes, in figure
    coordinates."""
    inv = fig.transFigure.inverted()
    xs = [ax.get_position().x0]
    for t in ax.get_yticklabels():
        if t.get_visible() and t.get_text():
            xs.append(inv.transform_bbox(t.get_window_extent(rend)).x0)
    lab = ax.yaxis.get_label()
    if lab.get_text():
        xs.append(inv.transform_bbox(lab.get_window_extent(rend)).x0)
    return min(xs)


def stamp(fig, items, pad_x=0.013, pad_y=0.011, size=10):
    """Grid-aligned panel letters.

    items: [(ax, "a"), ...] or [(ax, "a", (dx, dy)), ...] for a local nudge.
    Panels in one gridspec column share an x (the leftmost y-axis decoration boundary in that
    column, shifted left by pad_x), and panels in one row share a y (the top edge of that
    row's axes, shifted up by pad_y).
    """
    fig.canvas.draw()
    rend = fig.canvas.get_renderer()
    rows: dict[float, list[float]] = {}
    cols: dict[float, list[float]] = {}
    rec = []
    for it in items:
        ax, letter = it[0], it[1]
        dx, dy = it[2] if len(it) > 2 else (0.0, 0.0)
        bb = ax.get_position()
        ck, rk = round(bb.x0, 3), round(bb.y1, 3)
        cols.setdefault(ck, []).append(_ydeco_left(ax, fig, rend))
        rows.setdefault(rk, []).append(bb.y1)
        rec.append((letter, ck, rk, dx, dy))
    for letter, ck, rk, dx, dy in rec:
        fig.text(min(cols[ck]) - pad_x + dx, max(rows[rk]) + pad_y + dy, letter,
                 fontsize=size, fontweight="bold", va="bottom", ha="left")


def panel(ax, letter, dx=-0.16, dy=1.06):
    """The old single-panel letter; still used only for the loose SI figures that do not sit
    on a grid."""
    ax.text(dx, dy, letter, transform=ax.transAxes, fontsize=10,
            fontweight="bold", va="top", ha="left")


def save(fig, name):
    fig.savefig(OUT / f"{name}.pdf")
    fig.savefig(OUT / f"{name}.svg")
    fig.savefig(OUT / f"{name}.png", dpi=400)
    plt.close(fig)
    print("wrote", name)


def _split(split="calibration"):
    d = pd.read_csv(SI_DATA / "s5_split_consistency.csv")
    return d[d.split == split].set_index("ruleset")


# ─────────────────────────────────────────────────────────────────────────────
# Fig. 2 -- the discovered laws: list them all at once, then look at their joint performance
# ─────────────────────────────────────────────────────────────────────────────
RULES = [
    ("Law 1", r"$\rho \geq \tau$",
     "shortest cation–anion contact, relative to the radius sum",
     {"L1": "0.735", "L1'": "0.735", "L2": "0.804", "L3": "0.804", "L4": "0.804"}),
    ("Law 2", r"if  $f_{\mathrm{i}} > 0.50$   then   $\rho \leq 1.05$",
     "ionicity condition: an upper bound applied only where the ionic model holds",
     {"L1'": "•"}),
    ("Law 3", r"if  mean anion CN $\leq$ 3.333   then   mean $d/(r_{\mathrm{cat}}{+}r_{\mathrm{an}}) \leq 1.081$",
     "low-coordination structures may not also be loosely packed on average",
     {"L2": "•", "L3": "•", "L4": "•"}),
    ("Law 4", r"range of  $E_{\mathrm{M}}/|z|$  across sites  $\leq$ 31.45",
     "no site may be electrostatically far out of line with the others",
     {"L2": "•", "L3": "•", "L4": "•"}),
    ("Law 5", r"$\mathrm{max}_i\ E_{\mathrm{M}}(i) \leq$ 15.17",
     "no single site may have an implausible Madelung energy",
     {"L2": "•", "L3": "•", "L4": "•"}),
    ("Law 6", r"if  $f_{\mathrm{i}} > 0.55$   then   no like-charge bonds",
     "charge topology: ionic compounds do not bond like to like",
     {"L3": "•", "L4": "•"}),
    ("Law 7", r"inequivalent sites / sites $\leq 2/3$",
     "distinct-site bound consistent with a preference for simpler structures",
     {"L4": "•"}),
    ("Law 8", r"mean relative bond-valence deviation $\leq$ 0.7143",
     "a permissive tail bound on the valence sum, the quantity of rule 2",
     {"L4": "•"}),
]
SETS = ["L1", "L1'", "L2", "L3", "L4"]
# uniform two/three-line labels for the five perturbation classes (shared by Fig 2c and
# Fig 4b, with matching line counts so they align)
CLASSLAB = ["D1\nuniaxial\ncompression", "D2\ncation–cation\nswap",
            "D3\nrandom\ndisplacement", "D4\nisotropic\nexpansion",
            "D5\ncation–anion\nswap", "all five\nclasses\npooled"]
# a law set is named after the model the whole set requires, not after the law it adds:
# hard-sphere -> rigid-ion lattice -> ionic network -> crystal chemistry,
# each one contains the previous. Column centres are only 1.43 cm apart, so no line exceeds
# 11 characters.
# Set 1' does not repeat "hard-sphere": with columns 1.43 cm apart, the same word side by
# side leaves only 0.9 mm of clear space and reads as one string. "two-sided" matches the
# main text word for word.
SETNAME = {"L1": "hard-sphere\nfloor", "L1'": "two-sided\nwindow",
           "L2": "rigid-ion\nlattice", "L3": "ionic\nnetwork",
           "L4": "crystal\nchemistry"}


def fig2():
    cal = _split("calibration")
    _W, _H = 18.3, 12.45
    FH = _H * CM
    fig = plt.figure(figsize=(W2, FH))
    # explicit panel rectangles (cm -> figure fraction); row heights are allotted by the
    # leading each enlarged font needs. The two data rows have different column widths (d/e
    # have far longer y labels than b/c), but the x0 of the left and right columns is kept
    # identical so stamp's column logic still aligns a/b/d and c/e separately.
    # The total height is constrained by the layout: this page's float barely fits as it is
    # (see the [p] caption in body.tex), so the figure must not exceed the pre-revision
    # 20.3 cm mark, or the caption runs into the page number.
    def _rect(x0, w, ytop, h):
        return [x0 / _W, (_H - ytop - h) / _H, w / _W, h / _H]

    # two panels per column: a/c share the left column [X1, X1R] and b/d the right [X2, XR];
    # the 2.00 cm between them is for d's constant labels (right-aligned against the right
    # column's y-axis).
    X1, X1R, X2, XR = 1.95, 7.60, 9.85, 17.95
    YB, HB_ = 0.50, 4.25
    YC, HC_ = 6.35, 4.95

    # ---- (a) satisfaction–damage-detection plane, discovery split
    axb = fig.add_axes(_rect(X1, X1R - X1, YB, HB_))
    cf = pd.read_csv(DATA / "fig3_certified_frontier.csv").sort_values("sat")
    hcert, = axb.plot(cf.sat, cf.excl, "-", color="#9A9C9F", lw=1.1, zorder=1,
                      label="provably optimal decision trees (depth $\\leq$ 3)")
    # the scatter on the frontier is just "nodes on a line": keep the markers small, otherwise
    # they merge with the adjacent law-set markers (L1'/L2 sit only 0.02--0.06 data units from
    # a frontier point) into a two-coloured blob.
    axb.scatter(cf.sat, cf.excl, s=9, c="#9A9C9F", ec="w", lw=0.5, zorder=2)

    fr = pd.read_csv(DATA / "fig2_frontier.csv").dropna(subset=["exclusion"])
    fr = fr.sort_values("satisfaction")
    # a short dash period: the frontier spans only 0.1 cm between L1' and L1, where long
    # dashes leave two isolated smudges, while fine dashes clearly read as part of one dashed
    # line.
    hbeam, = axb.plot(fr.satisfaction, fr.exclusion, color="#D0D2D5", lw=0.9,
                      ls=(0, (3.0, 1.6)), zorder=1,
                      label="systematic search over law combinations")
    axb.scatter(fr.satisfaction, fr.exclusion, s=8, c="#D0D2D5", ec="w", lw=0.4,
                zorder=2)
    # tuck the legend into the top-right of the data area: once the panel narrowed, the right
    # edge of the legend that used to hang outside the axes collided with the right column's
    # panel letter. Raising the top by another 0.09 units opens up space between the legend
    # and the frontier curve.
    axb.legend(handles=[hcert, hbeam], frameon=False, fontsize=7.15,
               loc="upper right", handlelength=1.5, handletextpad=0.6,
               borderpad=0.1, labelspacing=0.35, bbox_to_anchor=(1.0, 1.005))

    dis = _split("discovery")
    mks = {"L1": ("o", (2, -13)), "L1'": ("s", (-17, -3)),
           "L2": ("o", (-1, -13)), "L3": ("o", (2, -13)),
           "L4": ("D", (4, -13))}
    for s in SETS:
        m, off = mks[s]
        axb.scatter([dis.loc[s, "sat"]], [dis.loc[s, "excl"]], s=52, c=SETC[s],
                    ec="w", lw=0.8, zorder=5, marker=m)
        # At the base 8.5 pt these five in-plot labels were the largest type in
        # the figure and read as headings rather than as point labels.  Match
        # the row labels of panel d instead.
        axb.annotate(setlab(s), (dis.loc[s, "sat"], dis.loc[s, "excl"]),
                     textcoords="offset points", xytext=off, fontsize=7.6,
                     color=SETC[s], ha="center")
    p = pd.read_csv(DATA / "fig2_pauling_structure.csv")
    # Pauling 2--5 has measured satisfaction but no damage-detection value on this
    # damage benchmark.  Do not place it on the two-axis plane using a proxy
    # coordinate; the measured satisfaction comparison is shown separately in (c).
    axb.set_xlim(0.795, 1.004); axb.set_ylim(0.0, 1.20)
    axb.set_yticks([0, 0.2, 0.4, 0.6, 0.8, 1.0])
    axb.spines["left"].set_bounds(0, 1.0)
    axb.set_xlabel("Satisfaction of experimental structures\n(discovery split)",
                   labelpad=2.0, linespacing=1.3)
    axb.set_ylabel("Damage detection", labelpad=4.0,
                   linespacing=1.3)

    # ---- (b) profile by damage type for the four sets, held-out split
    axc = fig.add_axes(_rect(X2, XR - X2, YB, HB_))
    KS = ["S1", "S2", "S3", "S4", "S5"]
    x = np.arange(6)
    bar_width, bar_step = 0.190, 0.135
    for k, s in enumerate(SETS):
        v = [float(cal.loc[s, c]) for c in KS] + [float(cal.loc[s, "excl"])]
        bars = axc.bar(
            x + (k - 2.0) * bar_step,
            v,
            bar_width,
            color=SETC[s],
            edgecolor=SETC[s],
            linewidth=0.85,
            label=setlab(s),
            zorder=3.0 - 0.10 * k,
        )
        # Keep the fill only slightly lighter than the fully opaque, same-hue
        # outline.  Set the patch properties separately because the shared
        # palette wrapper caps artist-level alpha and would otherwise fade the
        # outline together with the interior.
        style_bar_container(bars, SETC[s], opaque_fill_weight=0.55)
    axc.axvline(4.5, color="#B9BBBE", lw=0.7, ls=":")
    axc.set_xlim(-0.60, 5.50)
    axc.set_xticks(x)
    axc.set_xticklabels(
        [dmglab(k) for k in KS] + ["All"],
        fontsize=plt.rcParams["ytick.labelsize"],
    )
    axc.set_ylabel("Damage detection\n(held-out data)", labelpad=4.0,
                   linespacing=1.3)
    axc.set_ylim(0, 1.05)
    axc.set_yticks([0, 0.2, 0.4, 0.6, 0.8, 1.0])
    axc.legend(frameon=False, fontsize=7.8, ncol=5, loc="upper left",
               handlelength=1.0, columnspacing=1.0, borderpad=0.1,
               bbox_to_anchor=(-0.015, 1.13))

    # ---- (c) structure-level comparison on the same held-out experimental structures
    axd = fig.add_axes(_rect(X1, X1R - X1, YC, HC_))
    pa = p.set_index("rule")
    PAU, PAUJ = "#989A9D", "#585A5C"     # neutral greys: within this figure colour identifies
                                         # a law set and nothing else
    # The separate historical audit uses site-orbit, orbit-pair and structure
    # denominators and therefore cannot support a common-axis comparison here.
    # These rows instead apply each Pauling criterion at structure level to the
    # same 5,297 held-out structures used for the PRIS bars.
    rows = [("Pauling 2", float(pa.loc["Pauling 2", "satisfaction"]), np.nan, PAU),
            ("Pauling 3", float(pa.loc["Pauling 3", "satisfaction"]), np.nan, PAU),
            ("Pauling 4", float(pa.loc["Pauling 4", "satisfaction"]), np.nan, PAU),
            ("Pauling 5", float(pa.loc["Pauling 5", "satisfaction"]), np.nan, PAU),
            ("Pauling 2–5\njointly",
             float(pa.loc["Pauling 2-5 jointly", "satisfaction"]), np.nan, PAUJ)]
    rows += [(setlab(s), float(cal.loc[s, "sat"]), np.nan, SETC[s])
             for s in SETS]
    # row positions are not evenly spaced: "Pauling 2--5 / jointly" is the only two-line tick
    # label in this panel, and evenly spaced its two lines each eat 0.05 cm of the neighbouring
    # rows' clear space. Adding 0.30 units before and after gives it the same clear space as
    # every other row (about 0.15 cm).
    yy = np.array([9.6, 8.6, 7.6, 6.6,             # Pauling 2--5
                   5.35,                           # Pauling 2--5 jointly
                   4.0, 3.0, 2.0, 1.0, 0.0])       # L1 ... L4
    satisfaction_bars = axd.barh(
        yy,
        [r[1] for r in rows],
        color=[r[3] for r in rows],
        height=0.66,
        lw=0,
    )
    style_bar_container(satisfaction_bars, [r[3] for r in rows])
    for i, (lab, v, vhi, c) in enumerate(rows):
        if not np.isnan(vhi) and vhi > v + 1e-9:
            axd.plot([v, vhi], [yy[i]] * 2, color="#535557", lw=0.7, zorder=4)
            axd.plot([vhi] * 2, [yy[i] - 0.17, yy[i] + 0.17], color="#535557",
                     lw=0.7, zorder=4)
        axd.text(max(v, 0 if np.isnan(vhi) else vhi) + 0.016, yy[i], f"{v:.3f}",
                 va="center", fontsize=7.5, color="#535557" if c == PAU else c)
    axd.set_yticks(yy)
    axd.set_yticklabels([r[0] for r in rows], fontsize=7.2, linespacing=1.05,
                        ha="right", multialignment="right")
    axd.tick_params(axis="y", pad=2.5)
    axd.set_xlim(0, 1.12); axd.set_xticks([0, 0.2, 0.4, 0.6, 0.8, 1.0])
    axd.set_xlabel("Structure-level satisfaction\n(5,297 held-out crystals)")
    # the separator sits midway between the descender of "jointly" and the cap height of L1,
    # leaving 0.08 cm on each side
    axd.axhline(4.50, color="#B9BBBE", lw=0.7)

    # ---- (d) do the constants remain stable? re-derive each bound at the same percentile
    #          on the held-out split and compare with the selected value
    axe = fig.add_axes(_rect(X2, XR - X2, YC, HC_))
    tr = json.loads((ROOT / "outputs" / "20260815_threshold_transfer"
                     / "transfer.json").read_text())
    # The archive keys retain their historical labels; RLABE below controls the
    # scientifically corrected text shown in the figure.
    KEY = ["D1 tau=0.735 (rho)", "D1 tau=0.804 (rho)", "D2 1.05 (rho, ionic)",
           "D3 1.081 (mean d/rsum)", "D4 31.45 (range VM/z)", "D5 15.17 (max VM)",
           "D7 2/3 (economy)", "D8 0.714 (BV dev)"]
    RLABE = [r"Law 1   $\tau$ = 0.735", r"Law 1   $\tau$ = 0.804", "Law 2   1.05",
             "Law 3   1.081", "Law 4   31.45", "Law 5   15.17", "Law 7   2/3",
             "Law 8   0.7143"]
    XTXT = 1.315                       # verdict-column anchor
    NEU = "#535557"
    # Reuse only colours already established in panels a--c.  Laws 1--4 retain
    # the corresponding set identities; laws without a set identity are neutral.
    ROWC = [BLU, BLU, ORA, RED, SETC["L4"], NEU, NEU, NEU]
    LAW_NUMBERS = (1, 1, 2, 3, 4, 5, 7, 8)
    LAW_MARKERS = ("o", "s", "^", "D", "v", "P", "X", "h")
    yy = np.arange(len(KEY))[::-1]
    # the reference line only spans the height of the data rows: a full-height axvline would
    # run from the header above all the way into the legend text below. Its bounds match the
    # left spine's set_bounds.
    axe.plot([1.0, 1.0], [-0.30, len(KEY) - 0.70], color="#B9BBBE", lw=0.7,
             zorder=1, solid_capstyle="butt")
    for k, y, row_colour, law_number, law_marker in zip(
        KEY, yy, ROWC, LAW_NUMBERS, LAW_MARKERS, strict=True
    ):
        d = tr[k]
        r = d["calib_value"] / d["threshold"]
        impact_colour = RED if abs(d["verdict_flip_real_pct"]) >= 1.0 else row_colour
        if abs(r - 1.0) > 1e-9:
            axe.plot([1.0, r], [y, y], color=to_rgba(row_colour, 0.58),
                     lw=1.0, zorder=2, solid_capstyle="butt")
            axe.scatter(
                [r], [y], s=26, marker=law_marker,
                facecolors=to_rgba(row_colour, 0.12),
                edgecolors=row_colour, lw=1.0, zorder=4, clip_on=False,
            )
            # Full linear scaling makes the small D1--D3 shifts nearly overlap the
            # fixed point.  Put the number on the side away from unity so that the
            # label remains readable without magnifying the displacement itself.
            sgn = 1.0 if r >= 1.0 else -1.0
            axe.text(r + sgn * 0.022, y, f"{d['calib_value']:.3g}",
                     fontsize=7.0, color=row_colour, va="center",
                     ha="left" if sgn > 0 else "right")
        else:
            axe.scatter(
                [1.0], [y], s=34, marker=law_marker, facecolors="none",
                edgecolors=row_colour, lw=0.9, zorder=4,
            )
            axe.text(1.022, y, "identical", fontsize=7.0, color=row_colour, ha="left",
                     va="center")
        # the filled point for the frozen constant is drawn over the white fill of the open
        # circle, with a white outline; the open circle's outline is then redrawn on top. At
        # their closest the two markers differ by only 0.6% (about 0.1 cm), so this keeps the
        # ring complete and makes the filled point look laid over it rather than biting a
        # piece out of it.
        fixed_marker = axe.scatter(
            [1.0], [y], s=13, marker=law_marker,
            c=row_colour, ec="w", lw=0.5, zorder=5,
        )
        fixed_marker.set_gid(f"fig2d-fixed-law-{law_number}")
        if abs(r - 1.0) > 1e-9:
            axe.scatter(
                [r], [y], s=26, marker=law_marker, facecolors="none",
                edgecolors=row_colour, lw=1.0, zorder=6, clip_on=False,
            )
        axe.text(XTXT, y, f"{d['verdict_flip_real_pct']:.2f}", fontsize=7.6,
                 color=impact_colour,
                 ha="right", va="center")

    # The main row plot shows how far each frozen constant moves.  This inset
    # uses the otherwise empty upper-left region to answer a different question:
    # whether re-derivation changes experimental and chemically damaged verdicts
    # in the same way.  A common 0--20% scale resolves every measured change
    # while retaining ample headroom above the observed sub-8% range.
    impact = axe.inset_axes([0.170, 0.615, 0.340, 0.295])
    impact.set_label("Fig2d-transfer-impact")
    real_flip = np.array([tr[key]["verdict_flip_real_pct"] for key in KEY])
    damaged_flip = np.array(
        [tr[key]["verdict_flip_corrupted_pct"] for key in KEY]
    )
    impact.plot(
        [0.0, 20.0], [0.0, 20.0], color="#B9BBBE", lw=0.6,
        ls=(0, (2.5, 1.8)), zorder=1,
    )
    for x, y, colour, marker, law_number in zip(
        real_flip, damaged_flip, ROWC, LAW_MARKERS, LAW_NUMBERS, strict=True
    ):
        impact_marker = impact.scatter(
            [x], [y], s=18, marker=marker,
            facecolors=to_rgba(colour, 0.14),
            edgecolors=to_rgba(colour, 0.96), linewidths=0.60,
            zorder=4, clip_on=False,
        )
        impact_marker.set_gid(f"fig2d-impact-law-{law_number}")

    # Marker shape already identifies the law in both the main panel and this
    # inset, so the points carry no per-point label: five of them sit within
    # 1.7 percentage points of the origin, where the numbers and their leader
    # lines cost more legibility than they returned.
    impact.set_xlim(-0.4, 20.4)
    impact.set_ylim(-0.4, 20.4)
    impact.set_xticks([0, 10, 20])
    impact.set_yticks([0, 10, 20])
    impact.set_xlabel("Experimental flips (%)", fontsize=7.2, labelpad=1.2)
    impact.set_ylabel("Damaged flips (%)", fontsize=7.0, labelpad=1.0)
    impact.tick_params(labelsize=6.8, width=0.45, length=2.0, pad=1.2)
    for spine in impact.spines.values():
        spine.set_linewidth(0.45)
        spine.set_zorder(0.5)
    impact.spines["top"].set_visible(False)
    impact.spines["right"].set_visible(False)
    axe.set_yticks(yy); axe.set_yticklabels(RLABE, fontsize=7.6, ha="right")
    axe.tick_params(axis="y", pad=2.5)
    axe.set_ylim(-0.95, len(KEY) + 0.20)
    axe.set_xlim(0.14, 1.34)
    axe.set_xticks([0.2, 0.4, 0.6, 0.8, 1.0, 1.2])
    axe.set_xlabel("Re-derived / fixed constant", labelpad=1.5)
    axe.spines["bottom"].set_bounds(0.20, 1.20)
    axe.spines["left"].set_bounds(-0.30, len(KEY) - 0.70)
    axe.text(XTXT, len(KEY) - 0.35, "experimental-structure\nverdicts flipped (%)", fontsize=7.4,
             color=NEU, ha="right", va="bottom", linespacing=1.30)
    axe.text(0.205, -0.60, "filled = fixed before testing      open = re-derived", fontsize=7.4,
             color="#535557", ha="left", va="center")

    stamp(fig, [(axb, "a"), (axc, "b"),
                (axd, "c"), (axe, "d")])
    save(fig, "fig2_rules")


# ─────────────────────────────────────────────────────────────────────────────
# Fig. 1 — Agentic law learning: the loop, its scale, and its refutation ledger
# ─────────────────────────────────────────────────────────────────────────────
def _rule_table(ax, cal, W, H):
    """The complete catalogue of D1--D8 and the five nested law sets (formerly Fig. 2a, now
    Fig. 1d).

    The coordinate system is in centimetres directly: x runs 0..W to the right and y runs
    0..H downwards. Row heights therefore follow from the font size, the type does not stretch
    when the panel is widened or heightened, and any extra height becomes inter-row space.
    """
    ax.set_xticks([]); ax.set_yticks([])     # so stamp picks up the panel frame rather than
                                             # hidden ticks
    ax.axis("off")
    ax.set_xlim(0, W); ax.set_ylim(H, 0)
    xc = [W * f for f in (0.628, 0.708, 0.788, 0.868, 0.948)]
    x0, x1 = 0.0, W          # the table rules and zebra striping align exactly with the left
                             # and right edges of panel a's flow boxes
    # with the number column changed from D1--D8 to Law 1--Law 8 it is about 0.35 cm wider, so
    # the expression column moves right to 0.078W; otherwise the last character of "Law 1"
    # runs into the first character of the formula behind it.
    XR, XG = 0.014 * W, 0.078 * W            # the law-number column; the expression and gloss columns
    # the header height has to fit the three lines "L1 / contact / floor": at 0.95 the third
    # line's baseline sits exactly on the table's top rule and merges with it in print. 1.12
    # gives about 0.15 cm of clear space.
    HHEAD, HSUM, HGAP = 1.12, 0.38, 0.20     # header / per-row summary / clear space above the separator
    DY = 0.135                               # offset of the expression and gloss lines from the row centre
    HRULE = (H - HHEAD - HGAP - 2 * HSUM) / len(RULES)

    # the header labels drop to 0.32: 0.11 cm between the names and the top rule, and 0.22 cm
    # from c's axis title above -- so the labels clearly belong to the table below rather than
    # floating between the two.
    yh = 0.32
    for x, s in zip(xc, SETS):
        c = SETC[s]
        ax.text(x, yh, setlab(s, "$'$"), fontsize=9.2,
                color=c, ha="center", va="center")
        ax.text(x, yh + 0.53, SETNAME[s], fontsize=7.2, color=c, ha="center",
                va="center", linespacing=1.30)
    ax.plot([x0, x1], [HHEAD] * 2, color="#323335", lw=0.8)

    y = HHEAD
    for i, (rid, expr, gloss, member) in enumerate(RULES):
        if i % 2 == 0:
            ax.add_patch(mp.Rectangle((x0, y), x1 - x0, HRULE, fc="#EEF2F5",
                                      lw=0, zorder=0, clip_on=False))
        yc = y + HRULE / 2                  # row centre: membership markers land here
        ye = yc - DY                        # the expression line, centred symmetrically with the gloss
        ax.text(XR, ye, rid, fontsize=8.6,
                color="#212224", va="center")
        ax.text(XG, ye, expr, fontsize=8.8, color="#101113", va="center")
        ax.text(XG, yc + DY, gloss, fontsize=7.1, color="#535557",
                va="center", style="italic")
        for x, s in zip(xc, SETS):
            mk = member.get(s)
            if mk is None:
                ax.text(x, yc, "–", fontsize=7.4, color="#CACCCF", ha="center",
                        va="center")
            elif mk == "•":
                ax.scatter([x], [yc], s=30, c=SETC[s], lw=0, zorder=3,
                           transform=ax.transData)
            else:
                ax.text(x, yc, mk, fontsize=7.4, color=SETC[s], ha="center",
                        va="center")
        y += HRULE

    ax.plot([x0, x1], [y + HGAP] * 2, color="#323335", lw=0.8)
    y += HGAP
    for lab, key, fmt in [("satisfaction (experimental structures)", "sat", "{:.4f}"),
                          ("damage detection", "excl", "{:.4f}")]:
        y += HSUM
        ax.text(XG, y - 0.16, lab, fontsize=8.3, color="#323335", va="center")
        for x, s in zip(xc, SETS):
            ax.text(x, y - 0.16, fmt.format(float(cal.loc[s, key])), fontsize=8.3,
                    color=SETC[s], ha="center", va="center")



def _fig1_rulespace(ax):
    """Panel b: a t-SNE projection of the 2,047,123 candidate laws, with nothing but the
    scatter and markers for the eight surviving laws.

    The data is the 220x220 count grid aggregated by
    experiments/rule_space_tsne/aggregate_for_fig1.py (the raw 2M-row projection is not
    archived). No colouring by topic and no explanatory text inside the panel: how to read it
    is left to the caption, and the scale to panel c.
    """
    from matplotlib.colors import LogNorm
    g = pd.read_csv(DATA / "fig1_rulespace_grid.csv")
    st = pd.read_csv(DATA / "fig1_rulespace_stars.csv")

    # density is drawn as a scatter, not with imshow: the panel is a wide rectangle and
    # imshow's cells would stretch into short dashes, whereas scatter markers are drawn in
    # display space and stay circular however the axes are stretched. Semi-transparent overlap
    # then shows the density on its own.
    order = np.argsort(g.n.values)                 # sparse first, dense drawn over the top
    norm = LogNorm(vmin=1, vmax=g.n.max())
    point_colours = plt.get_cmap("palseq")(norm(g.n.values[order]))
    point_faces = point_colours.copy()
    point_edges = point_colours.copy()
    point_faces[:, 3] = 0.24
    point_edges[:, 3] = 0.64
    ax.scatter(
        g.x.values[order], g.y.values[order], s=1.8,
        facecolors=point_faces, edgecolors=point_edges,
        linewidths=0.18, zorder=1,
    )

    # the eight surviving laws: the fill alone is lightened while the white border stays fully
    # opaque; both the point cloud and the markers stay vector paths, so zooming the PDF never
    # shows a blurred 400-dpi raster layer.
    ax.scatter(
        st.x,
        st.y,
        s=30,
        facecolors=[to_rgba(RED, 0.34)],
        edgecolors="white",
        linewidths=1.30,
        zorder=4,
    )

    # the eight laws fall into four distinguishable blobs on the t-SNE, and each blob gets one
    # leader line and one label.
    # The names always go outside the point cloud: a blank column is left at the right end of
    # the x axis, the labels are set there, and only the leader lines enter the cloud.
    # Panel c's category labels sit right against that column, so a label must not cross the
    # panel's own right edge.
    P = {r.rule: (r.x, r.y) for r in st.itertuples()}
    # runs of consecutive laws are written as ranges: eight names crowded the embedding they
    # point into, and the leader lines are what identify the clusters
    # D6/D7 sit about one marker width to the left of D1/D3/D8, so their leader has to
    # end on the marker itself: a 3-pt shrink would retract its tip onto the neighbouring
    # cluster and label the wrong blob.
    groups = [(["D2"], "Law 2", (138, 104)),
              (["D1", "D3", "D8"], "Law 1, 3, 8", (138, 36)),
              (["D6", "D7"], "Law 6–7", (138, -32)),
              (["D4", "D5"], "Law 4–5", (138, -100))]
    for names, lab, (tx, ty) in groups:
        xs = float(np.mean([P[n][0] for n in names]))
        ys = float(np.mean([P[n][1] for n in names]))
        ax.annotate(lab, xy=(xs, ys), xytext=(tx, ty), textcoords="data",
                    fontsize=7.2, color=RED,
                    ha="left", va="center", zorder=6, annotation_clip=False,
                    linespacing=1.25,
                    arrowprops=dict(arrowstyle="-", lw=0.6, color=RED,
                                    shrinkA=1.0, shrinkB=1.0))

    # the x axis extends just far enough to hold that label column: any wider and the point
    # cloud shrinks for nothing, any narrower and the labels hit panel c's category labels.
    # The longest, "Law 1, 3, 8", is about 1.3 cm, and the column width is set from it.
    ax.set_xlim(-136.0, 178.0)
    ax.set_ylim(-142.0, 142.0)
    ax.set_xticks([]); ax.set_yticks([])
    # the axis title carries the scale: the point cloud here is the 2,047,123 candidate laws
    # before aggregation
    ax.set_xlabel(
        r"Explored $2\times10^{6}$ law space", labelpad=2.0,
        fontsize=plt.rcParams["axes.labelsize"],
    )
    # the axis title follows the point cloud, not the panel centre line, which now sits right
    # of it
    ax.xaxis.set_label_coords((0.0 + 136.0) / 314.0, -0.052)
    for sp in ax.spines.values():
        sp.set_visible(False)


def _fig1_trajectory(ax, fig, inset_rect):
    at = pd.read_csv(DATA / "fig1_attempts.csv")

    def steps(ms, x_end):
        xs, ys = [ms[0][0]], [ms[0][1]]
        for r, v in ms[1:]:
            xs += [r, r]; ys += [ys[-1], v]
        xs.append(x_end); ys.append(ys[-1])
        return xs, ys

    MS = [(1, 0.0), (4, 0.2890), (13, 0.6121), (14, 0.7004)]
    xs, ys = steps(MS, 594)
    ax.plot(xs, ys, color=BLU, lw=1.6, zorder=4,
            label="best damage detection at satisfaction $\\geq$ 0.90")
    # the dash period is chosen from the total length of this polyline: at (4,2) the last
    # segment leaves only 1 pt of ink, hanging between the L4 marker and the L4 label like a
    # speck of dirt. (5,2.2) ends on a whole segment.
    ax.plot([560, 585, 585, 594], [0.7004, 0.7004, 0.8180, 0.8180],
            color="#0A5A3C", lw=1.6, ls=(0, (5, 2.2)), zorder=4,
            label="best lower of satisfaction and damage detection")
    ax.scatter([585], [0.8180], s=22, c="#0A5A3C", zorder=6)
    # the two curves differ by only 0.118, so each label sits on the outer side of its own
    # curve to keep the two from overlapping
    ax.text(598, 0.688, "Set 3", fontsize=9, color=BLU, va="top")
    ax.text(598, 0.830, "Set 4", fontsize=9, color="#0A5A3C", va="bottom")

    # ---- attempt strip: each round's own gate verdict
    # rounds that passed get a lane of their own: they previously shared a y with "failed its
    # gate", which put the green triangle right beside the red label and made it read as that
    # label's legend key.
    # Lane spacing is set from the label font size: 0.15 data units = 0.31 cm > the 7.4 pt line
    # height, so the four right-hand labels no longer overlap (0.08 units gave only 0.18 cm).
    # Only lanes that actually receive a mark are drawn: a labelled empty lane points at blank
    # space.
    # Lane mapping: the outcome spellings in fig1_attempts.csv are aligned to the lane names.
    # Three classes are deliberately left unmarked, 175 rows in all; the reasons are in the
    # plotting conventions of SI Note S1:
    #   not-run (blocked upstream) 131  -- never executed, so there is no verdict of its own
    #   unmarked                    37  -- the archive holds no checkable verdict
    #   measurement                  7  -- a measurement rather than an attempt at a gate
    YPASS = -0.085
    LANES = {"fail": (-0.250, "#D6564C", "missed its criterion"),
             "nogain": (-0.400, "#35A7D8", "no gain"),
             "aband": (-0.550, "#8A8C8E", "abandoned")}
    GROUP = {"fail-gate": "fail", "no-eligible": "fail",
             "probe-pass": "nogain", "diagnostic-only": "nogain",
             "no-gain": "nogain",
             "mixed: D2 accepted, certified tree refuted out of distribution":
                 "nogain",
             "abandoned-family": "aband",
             "family-abandoned (redundancy stop)": "aband",
             "not-run (blocked upstream)": None,
             "measurement": None, "unmarked": None, "pass": "pass"}
    unmapped = sorted(set(at.outcome.astype(str).str.strip())
                      - set(GROUP)) if "outcome" in at else []
    if unmapped:                                   # a new spelling must not disappear silently
        raise ValueError(f"fig1 strip: unmapped outcomes {unmapped}")
    for _, row in at.iterrows():
        g = GROUP.get(str(row.outcome).strip(), None)
        x = row.unified_round
        if g in LANES:
            y, c, _ = LANES[g]
            ax.plot([x, x], [y - 0.046, y + 0.046], color=c, lw=0.6,
                    alpha=0.85, zorder=3)
        elif g == "pass":
            ax.scatter([x], [YPASS], s=13, marker="^", c="#0A5A3C", zorder=5)
    ax.text(598, YPASS, "met its criterion", fontsize=7.4, color="#0A5A3C",
            va="center")
    for y, c, lab in LANES.values():
        ax.text(598, y, lab, fontsize=7.4, color=c, va="center")

    ax.set_xlim(-4, 596); ax.set_ylim(-0.64, 1.04)
    ax.set_xticks([1, 100, 200, 300, 400, 500, 594])
    ax.set_xticklabels(["1", "100", "200", "300", "400", "500", "594"],
                       fontsize=8)
    ax.tick_params(axis="x", pad=2)
    ax.set_yticks([0, 0.5, 1.0]); ax.set_yticklabels(["0", "0.5", "1"],
                                                     fontsize=8)
    ax.set_xlabel("Investigation, unified programme index", labelpad=1.5)
    ax.set_ylabel("Best performance\n(held-out data)")
    ax.axhline(0, color="#CACCCF", lw=0.5, zorder=1)
    # the legend drops to 0.93: the curve plateaus at 0.80, so the legend lands in the gap
    # between that and the top of the panel, about 0.2 cm clear of the last row of table d
    # above, and no longer looks like it is floating between the two panels.
    ax.legend(frameon=False, fontsize=8, loc="lower left", handlelength=1.8,
              ncol=2, columnspacing=1.6, borderpad=0.1,
              bbox_to_anchor=(0.0, 0.93))
    ax.spines["left"].set_bounds(0, 1)

    # ---- inset: the first 24 investigations
    # the y axis runs to 1.45: of the three markers L3 sits at 0.70 and its label can only go
    # directly above it, and the label itself takes 0.43 units. The extra space at the top that
    # buys is filled by the axis title.
    axi = fig.add_axes(inset_rect)
    xs, ys = steps(MS, 24)
    axi.plot(xs, ys, color=BLU, lw=1.3, zorder=4)
    # every label stays clear of its own marker and its own step line: L1 goes above the 0.289
    # plateau, L2 sits to the left of its marker, and L3 is raised directly above its own.
    for r, v, lab, x, y, ha, va in [
            (4,  0.2890, "Set 1",  4.75, 0.400, "left",   "bottom"),
            (13, 0.6121, "Set 2", 12.20, 0.6121, "right", "center"),
            (14, 0.7004, "Set 3", 13.85, 0.870, "center", "bottom")]:
        axi.scatter([r], [v], s=14, c=BLU, ec="w", lw=0.5, zorder=6)
        axi.text(x, y, lab, fontsize=8.0, ha=ha, va=va,
                 color=BLU)
    for r in (15, 21):
        axi.scatter([r], [0.7004], s=13, facecolors="none", lw=0.9,
                    edgecolors="#35A7D8", zorder=6)
    axi.set_xlim(0, 26); axi.set_ylim(0, 1.45)
    axi.set_xticks([1, 8, 16, 24])
    axi.set_yticks([0, 0.5, 1.0]); axi.set_yticklabels(["0", "0.5", "1"])
    # the axis title tucks into the blank space at the top of the inset: outside the axes it
    # would have to squeeze into the 2 mm between the tick labels and the main panel's grey
    # y = 0 reference line.
    axi.text(0.025, 0.975, "first 24 investigations", transform=axi.transAxes,
             fontsize=6.8, color="#646668", ha="left", va="top")
    # the inset is visually subordinate to the main panel: thinner frame, lighter ticks
    axi.tick_params(labelsize=6.5, colors="#757779", width=0.4, length=2.0, pad=2.0)
    for lb in axi.get_xticklabels() + axi.get_yticklabels():
        lb.set_color("#646668")
    for sp in axi.spines.values():
        sp.set_linewidth(0.4); sp.set_color("#A8AAAD")
    ax.add_patch(mp.Rectangle((1, 0), 25, 0.74, fill=False, ec="#A8AAAD",
                              lw=0.6, ls=(0, (2, 2)), zorder=2))


# ─────────────────────────────────────────────────────────────────────────────
# Fig. 1a -- the discovery loop, and what the laws it produces are used for.
# This panel draws directly in centimetres with y downwards, the same coordinate convention as
# _rule_table: type does not stretch when the panel is widened or heightened, and any extra
# size becomes clear space. The upper half is the five-stage loop and the lower half the
# macroscopic input/output: candidate structure -> PRIS (eight one-line laws) -> plausible or
# implausible, naming the bound that was violated.
# The funnel in between joins the two halves -- the card in the lower half is the product of
# the loop above it.
# The refutation loop runs above the boxes: below is left for the funnel, so the two lines do
# not cross.
# The old grey band across the top (protocol + data splits) has been removed; the four split
# counts are in Methods.
# ─────────────────────────────────────────────────────────────────────────────
A_ANION, A_CATION = "#B4C4CE", "#005B93"     # anion / cation in the structure schematic
A_INK, A_MUTE = "#212224", "#535557"
A_EL, A_ER = 0.32, 18.22                     # left and right edges, shared with the full-width panels
H_FIG1A = 4.00                               # total height of panel a (cm)
H_STAGE = 1.26                               # height of the five flow boxes


def _rbox(ax, x, y, w, h, r=0.09, **kw):
    """A rounded rectangle whose outer edge is exactly (x, y, w, h): at pad=0 FancyBboxPatch
    does not expand outwards."""
    return ax.add_patch(mp.FancyBboxPatch(
        (x, y), w, h, boxstyle=f"round,pad=0,rounding_size={r}", **kw))


def _header_box(ax, x, y, w, h, hh, colour, r=0.09):
    """A card with a solid title bar. The bar is rounded on top and square below, so draw the
    rounded shape first and then flatten its lower edge with a rectangle."""
    _rbox(ax, x, y, w, h, r, lw=0.9, ec=colour, fc=colour + "12", zorder=2)
    _rbox(ax, x, y, w, hh, r, lw=0, fc=colour, zorder=3)
    ax.add_patch(mp.Rectangle((x, y + hh - r), w, r, lw=0, fc=colour, zorder=3))


def _arrow(ax, p0, p1, colour=A_MUTE, lw=1.0, ls="-", ms=8, z=4):
    ax.add_patch(mp.FancyArrowPatch(
        p0, p1, arrowstyle="-|>", mutation_scale=ms, lw=lw, ls=ls,
        color=colour, zorder=z, shrinkA=0, shrinkB=0))


def _caps(ax, x, y, s, size=6.0):
    """The small letterspaced grey type used for INPUT / OUTPUT: the letterspacing is done by
    inserting spaces and does not rely on any font feature."""
    ax.text(x, y, " ".join(s.upper()), ha="center", va="center", fontsize=size,
            color=GRY, zorder=5)


# ---- icons for the five loop stages. All drawn as paths rather than a symbol font, so no
# ---- glyph can go missing in the PDF/SVG -------------------------------------------------
def _ic_bulb(ax, x, y, s, c):
    lw = 0.8 * s / 0.24
    ax.add_patch(mp.Circle((x, y - 0.18 * s), 0.30 * s, fill=False, lw=lw, ec=c,
                           zorder=5))
    ax.plot([x - 0.16 * s, x + 0.16 * s], [y + 0.22 * s] * 2, lw=lw, color=c,
            solid_capstyle="round", zorder=5)
    ax.plot([x - 0.11 * s, x + 0.11 * s], [y + 0.40 * s] * 2, lw=lw, color=c,
            solid_capstyle="round", zorder=5)


def _ic_table(ax, x, y, s, c):
    w, h = 0.86 * s, 0.74 * s
    lw = 0.7 * s / 0.24
    ax.add_patch(mp.Rectangle((x - w / 2, y - h / 2), w, h, fill=False, lw=lw,
                              ec=c, zorder=5))
    ax.add_patch(mp.Rectangle((x - w / 2, y - h / 2), w, h / 3, lw=0, fc=c,
                              zorder=5))
    for f in (1 / 3, 2 / 3):
        ax.plot([x - w / 2, x + w / 2], [y - h / 2 + f * h] * 2, lw=lw * 0.8,
                color=c, zorder=5)
        ax.plot([x - w / 2 + f * w] * 2, [y - h / 2, y + h / 2], lw=lw * 0.8,
                color=c, zorder=5)


def _ic_lens(ax, x, y, s, c):
    lw = 0.85 * s / 0.24
    ax.add_patch(mp.Circle((x - 0.10 * s, y - 0.10 * s), 0.32 * s, fill=False,
                           lw=lw, ec=c, zorder=5))
    ax.plot([x + 0.13 * s, x + 0.40 * s], [y + 0.13 * s, y + 0.40 * s],
            lw=lw * 1.15, color=c, solid_capstyle="round", zorder=5)


def _ic_target(ax, x, y, s, c):
    lw = 0.8 * s / 0.24
    ax.add_patch(mp.Circle((x, y), 0.38 * s, fill=False, lw=lw, ec=c, zorder=5))
    ax.add_patch(mp.Circle((x, y), 0.14 * s, lw=0, fc=c, zorder=5))
    for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
        ax.plot([x + dx * 0.38 * s, x + dx * 0.56 * s],
                [y + dy * 0.38 * s, y + dy * 0.56 * s], lw=lw, color=c,
                solid_capstyle="round", zorder=5)


def _ic_refute(ax, x, y, s, c):
    lw = 0.85 * s / 0.24
    ax.add_patch(mp.Circle((x, y), 0.40 * s, fill=False, lw=lw, ec=c, zorder=5))
    d = 0.40 * s / np.sqrt(2)
    ax.plot([x - d, x + d], [y + d, y - d], lw=lw, color=c,
            solid_capstyle="round", zorder=5)


def _struct_glyph(ax, cx, cy, s=1.0, swap=False, n=3):
    """A small schematic of an ionic crystal: large anions, small cations, thin bond lines and
    a slight oblique projection.

    With swap=True, one pair swaps identity and is ringed in purple -- the same convention as
    the "transposed atoms" of Fig. 3a.
    """
    g = 0.20 * s
    xs = np.arange(n) - (n - 1) / 2
    pts = [(cx + i * g + 0.30 * g * j, cy + j * g) for j in xs for i in xs]
    for k, (px, py) in enumerate(pts):
        for m, (qx, qy) in enumerate(pts):
            if m <= k:
                continue
            if abs(np.hypot(qx - px, qy - py) - g) < 0.35 * g:
                ax.plot([px, qx], [py, qy], lw=0.45, color="#9AA5AC", zorder=4)
    for k, (px, py) in enumerate(pts):
        cation = (k % 2 == 1)
        if swap and k in (4, 5):
            cation = not cation
        ax.add_patch(mp.Circle((px, py), (0.062 if cation else 0.085) * s,
                               fc=A_CATION if cation else A_ANION,
                               ec="w", lw=0.4, zorder=5 + cation))
    if swap:
        for k in (4, 5):
            px, py = pts[k]
            ax.add_patch(mp.Circle((px, py), 0.135 * s, fill=False, lw=0.7,
                                   ec=ORA, zorder=7))


def _tick(ax, x, y, s, colour):
    ax.add_patch(mp.Circle((x, y), 0.115 * s, lw=0, fc=colour, zorder=5))
    ax.plot([x - 0.055 * s, x - 0.016 * s, x + 0.062 * s],
            [y + 0.004 * s, y + 0.046 * s, y - 0.048 * s],
            lw=0.95, color="w", solid_capstyle="round",
            solid_joinstyle="round", zorder=6)


def _cross(ax, x, y, s, colour):
    ax.add_patch(mp.Circle((x, y), 0.115 * s, lw=0, fc=colour, zorder=5))
    d = 0.048 * s
    ax.plot([x - d, x + d], [y - d, y + d], lw=0.95, color="w",
            solid_capstyle="round", zorder=6)
    ax.plot([x - d, x + d], [y + d, y - d], lw=0.95, color="w",
            solid_capstyle="round", zorder=6)


def _contact_glyph(ax, x, y, s=1.0):
    """Draw rho: two touching ions with a dimension line for d (the dimension line goes
    below)."""
    ra, rc = 0.175 * s, 0.105 * s
    ax.add_patch(mp.Circle((x - rc, y), ra, fc=A_ANION, ec="w", lw=0.5, zorder=4))
    ax.add_patch(mp.Circle((x + ra, y), rc, fc=A_CATION, ec="w", lw=0.5, zorder=5))
    yb = y + ra + 0.11 * s
    ax.plot([x - rc] * 2, [y, yb], lw=0.45, color=A_INK, zorder=5)
    ax.plot([x + ra] * 2, [y, yb], lw=0.45, color=A_INK, zorder=5)
    ax.add_patch(mp.FancyArrowPatch((x - rc, yb), (x + ra, yb),
                                    arrowstyle="<|-|>", mutation_scale=4.4,
                                    lw=0.65, color=A_INK, shrinkA=0, shrinkB=0,
                                    zorder=5))
    ax.text(x + (ra - rc) / 2, yb + 0.06 * s, "$d$", ha="center", va="top",
            fontsize=6.8, color=A_INK, zorder=5)


# the five loop stages. Two lines of explanation per box: at three lines the box width only
# allows 6.2 pt, whereas two lines fit at 6.9 pt.
STAGES = [
    ("PROPOSE",  "41 literature queries", "14 agent workflows",     BLU, _ic_bulb),
    ("TABULATE", "84 descriptor tables",  "99,162 structures",      BLU, _ic_table),
    ("SEARCH",   "one-line laws and",     "fitted thresholds",      ORA, _ic_lens),
    ("TEST",     "held-out data and",     "negative controls",      GRN, _ic_target),
    ("REFUTE",   "11 claims refuted",     "and returned to search", RED, _ic_refute),
]


def _fig1_engine(ax, ytop, h=H_STAGE, hh=0.40, arc=0.30):
    """The five-stage loop, left to right; the refutation loop runs above the boxes to leave
    room for the funnel below."""
    gap = 0.55                       # gap between boxes: any narrower and the arrows are too
                                     # short to read as directional
    bw = (A_ER - A_EL - 4 * gap) / 5
    cx = []
    for i, (name, l1, l2, c, icon) in enumerate(STAGES):
        x = A_EL + i * (bw + gap)
        cx.append(x + bw / 2)
        _header_box(ax, x, ytop, bw, h, hh, c)
        icon(ax, x + 0.42, ytop + hh / 2, 0.26, "w")
        # the title shifts right by 0.16: the icon occupies the left end of the title bar, and
        # without the shift "PROPOSE" looks off to the left
        ax.text(x + bw / 2 + 0.16, ytop + hh / 2 + 0.012, name, ha="center",
                va="center", color="w", fontsize=8.2, zorder=5)
        ax.text(x + bw / 2, ytop + hh + 0.30, l1, ha="center", va="center",
                fontsize=6.9, color="#323335", zorder=4)
        ax.text(x + bw / 2, ytop + hh + 0.61, l2, ha="center", va="center",
                fontsize=6.9, color="#323335", zorder=4)
        if i:
            _arrow(ax, (x - gap + 0.10, ytop + h / 2), (x - 0.10, ytop + h / 2),
                   colour="#6B6D6F", lw=1.0, ms=7.5)
    ya = ytop - arc
    ax.plot([cx[4], cx[4]], [ytop - 0.06, ya], color=RED, lw=1.0,
            ls=(0, (3.6, 2.0)), zorder=3)
    ax.plot([cx[0], cx[4]], [ya, ya], color=RED, lw=1.0, ls=(0, (3.6, 2.0)),
            zorder=3)
    _arrow(ax, (cx[0], ya), (cx[0], ytop - 0.06), colour=RED, lw=1.0,
           ls=(0, (3.6, 2.0)), ms=8, z=3)
    ax.text((cx[0] + cx[4]) / 2, ya - 0.08, "refuted claims re-enter the search",
            ha="center", va="bottom", fontsize=6.8, color=RED, zorder=4)


def _fig1_engine_io(ax):
    """Everything in panel a. The axes coordinates are already set to (0..18.3, H_FIG1A..0).

    0.67 cm must be left above the row of boxes: the dashed refutation loop plus its one line
    of explanation take 0.62 cm, and with less than that the text crosses the top of the panel,
    bbox_inches="tight" then crops the whole figure taller, the figure grows on the page, and
    the last line of the caption is pushed towards the page number.
    The lower edge has to leave clear space for the b/c panel letters: about 0.3 cm between the
    bottom of the card and the top of the letters; at 0.02 cm "candidate structures" and the
    letter b read as one line.
    """
    y_eng = 0.67
    _fig1_engine(ax, y_eng)
    y_eng_b = y_eng + H_STAGE

    XC, CW = 7.60, 5.90                      # the PRIS card
    # the funnel band widens from 0.38 to 0.56: "what survives refutation" previously had only
    # 0.07 cm above and below and read as pasted between the two rows of boxes; 0.56 gives the
    # line about 0.16 cm on each side.
    y0 = 2.55                                # top edge of the input/output band
    # the funnel: its top edge spans the whole row of boxes and its bottom narrows to the card
    # width, so it reads as "the product of this entire loop"
    ax.add_patch(mp.Polygon([[A_EL + 0.40, y_eng_b + 0.02],
                             [A_ER - 0.40, y_eng_b + 0.02],
                             [XC + (CW - 1.60) / 2, y0 - 0.04],
                             [XC - (CW - 1.60) / 2, y0 - 0.04]],
                            closed=True, fc="#EDF1F4", ec="#DDE2E7", lw=0.5,
                            zorder=1))
    ax.text(XC, (y_eng_b + y0) / 2 + 0.01, "what survives refutation",
            ha="center", va="center", fontsize=7.0, color="#45474A", zorder=3)

    # ---- input: any candidate structure (one ringed in purple, hinting at a controlled-damage
    # ---- variant)
    _caps(ax, 1.90, y0 - 0.16, "input")
    _struct_glyph(ax, 1.20, y0 + 0.62, 1.25)
    _struct_glyph(ax, 2.61, y0 + 0.62, 1.25, swap=True)
    ax.text(1.90, y0 + 1.20, "candidate structures", ha="center", va="center",
            fontsize=7.4, color=A_INK, zorder=5)
    _arrow(ax, (3.62, y0 + 0.68), (XC - CW / 2 - 0.16, y0 + 0.68),
           colour="#6B6D6F", lw=1.1, ms=8.5)

    # ---- the laws the loop produces; Law 1 is the example, with the geometry of rho drawn out
    _rbox(ax, XC - CW / 2, y0, CW, 1.40, 0.12, lw=1.1, ec=SLATE, fc="#F5F8FA",
          zorder=2)
    ax.text(XC - CW / 2 + 0.32, y0 + 0.35, "PRIS", ha="left", va="center",
            fontsize=10.5, color=SLATE, fontweight="bold", zorder=5)
    ax.text(XC - CW / 2 + 1.44, y0 + 0.37, "eight one-line laws, five mechanisms",
            ha="left", va="center", fontsize=7.4, color=A_MUTE, zorder=5)
    ax.plot([XC - CW / 2 + 0.28, XC + CW / 2 - 0.28], [y0 + 0.60] * 2,
            color="#DDE2E7", lw=0.6, zorder=3)
    ax.text(XC - CW / 2 + 0.34, y0 + 0.86, "e.g.", ha="left", va="center",
            fontsize=6.8, color=GRY, style="italic", zorder=5)
    _contact_glyph(ax, XC - CW / 2 + 1.22, y0 + 0.86, 1.05)
    ax.text(XC - CW / 2 + 1.86, y0 + 0.98,
            r"$\rho=\dfrac{d}{r_{\mathrm{cat}}+r_{\mathrm{an}}}\ \geq\ \tau$",
            ha="left", va="center", fontsize=8.6, color=A_INK, zorder=5)

    # ---- output: the two verdicts. The implausible box needs two lines and is therefore
    # ---- taller than the plausible one
    XV = 12.05
    _caps(ax, (XV + A_ER) / 2, y0 - 0.16, "output")
    _arrow(ax, (XC + CW / 2 + 0.16, y0 + 0.68), (XV - 0.20, y0 + 0.68),
           colour="#6B6D6F", lw=1.1, ms=8.5)
    _rbox(ax, XV, y0, A_ER - XV, 0.56, 0.10, lw=0.85, ec=GRN, fc=GRN + "12",
          zorder=2)
    _tick(ax, XV + 0.32, y0 + 0.28, 1.0, GRN)
    ax.text(XV + 0.62, y0 + 0.28, "plausible", ha="left", va="center",
            fontsize=8.2, color=GRN, zorder=5)
    ax.text(XV + 1.86, y0 + 0.29, "— every law satisfied", ha="left",
            va="center", fontsize=7.2, color=A_MUTE, zorder=5)
    _rbox(ax, XV, y0 + 0.68, A_ER - XV, 0.72, 0.10, lw=0.85, ec=RED,
          fc=RED + "12", zorder=2)
    _cross(ax, XV + 0.32, y0 + 1.04, 1.0, RED)
    ax.text(XV + 0.62, y0 + 1.04, "implausible", ha="left", va="center",
            fontsize=8.2, color=RED, zorder=5)
    ax.text(XV + 2.24, y0 + 0.89, "— names the violated law", ha="left",
            va="center", fontsize=7.2, color=A_MUTE, zorder=5)
    ax.text(XV + 2.24, y0 + 1.19, "and the mechanism to review", ha="left",
            va="center", fontsize=7.2, color=A_MUTE, zorder=5)


def fig1():
    cal = _split("calibration")
    # hard constraint on total height: this page is a [p] float with the caption immediately
    # below the figure, and anything past the text block runs into the page number. The cropped
    # PDF must be <= 20.6 cm tall (measured, at 20.5 the last caption line is still 0.2 cm clear
    # of the page number). The 1.41 cm a gained growing from 2.45 to 3.86 was taken from
    # b/c (-0.50), d (-0.08), e (-0.24) and three inter-panel gaps (-0.59), leaving the total
    # height unchanged at 20.35.
    _W, _H = 18.3, 20.35
    fig = plt.figure(figsize=(W2, _H * CM))

    def _rect(x0, w, ytop, h):
        return [x0 / _W, (_H - ytop - h) / _H, w / _W, h / _H]

    # explicit panel rectangles (cm). a/b/d share EL as their left edge and ER as their right;
    # e's plot area leaves room at the right for the lane labels, and its left edge is adjusted
    # below by the measured width of the y-axis decorations so that the left end of those
    # decorations also lands on EL -- that way stamp()'s column logic puts the a/b/d/e letters
    # on one line, while c (the only panel with y category labels) forms a column of its own.
    # The right edge is pushed to 18.22: the wider the cropped PDF, the smaller the \textwidth
    # scale factor, and the shorter the same layout height comes out on the page -- that is how
    # the clearance between the last caption line and the page number was won.
    EL, ER = 0.32, 18.22            # left and right edges of the full-width panels
    YA = 0.02                       # top edge of a: the panel provides its own top margin
    # the b/c row is squeezed to 3.29: b is an elliptical point cloud and the 0.66 cm removed
    # comes entirely from the blank above and below it; c's six bars still have 0.53 cm of
    # leading at 3.29. The top edge drops another 0.06 to make way for a's funnel band while
    # keeping at least 0.18 cm clear between a's card and the b/c letters.
    HBC, YBC = 3.29, 4.52           # height of the b/c row
    WB = 8.40                       # width of b: spread out horizontally so the scatter forms
                                    # an ellipse
    XC0 = 12.10                     # left edge of c's plot rectangle (the category labels are
                                    # right-aligned to it, and the longest label's left end must
                                    # clear b's right edge)
    XRT = 16.14                     # right edge of e's plot rectangle

    # ---- (a) the discovery loop, and what the loop produces
    # the panel rectangle spans the whole figure (0..18.3): the funnel narrows from the full row
    # of boxes to the card in the middle, and the narrower EL..ER rectangle cannot hold its two
    # upper corners. The internal coordinates are centimetres, with y downwards.
    axa = fig.add_axes(_rect(0.0, _W, YA, H_FIG1A))
    axa.set_xlim(0, _W); axa.set_ylim(H_FIG1A, 0)
    axa.set_xticks([]); axa.set_yticks([])
    axa.axis("off")
    _fig1_engine_io(axa)

    # ---- (b) the searched law space
    axe = fig.add_axes(_rect(EL, WB, YBC, HBC))
    _fig1_rulespace(axe)

    # ---- (c) scale of the autonomous run
    axb = fig.add_axes(_rect(XC0, ER - XC0, YBC, HBC))
    s = pd.read_csv(DATA / "fig1_agent_stats.csv").set_index("metric")["value"]
    keys = [("candidate_evaluations", "Candidate evaluations"),
            ("archived_result_files", "Result files archived"),
            ("scripts_written_total", "Analysis scripts written"),
            ("numbered_investigations", "Numbered investigations"),
            ("hypotheses_refuted", "Claims refuted by controls"),
            ("rules_surviving", "One-line laws surviving")]
    v = [float(s[k]) for k, _ in keys]; lab = [l for _, l in keys]
    col = [GRY, GRY, GRY, BLU, RED, "#0A5A3C"]
    scale_bars = axb.barh(
        np.arange(len(v))[::-1], v, color=col, height=0.62, lw=0,
    )
    style_bar_container(scale_bars, col)
    # the right end runs to 1.2e8: the largest value label, "2,037,606", is the rightmost ink in
    # the figure, and at 6e7 it crosses the ER edge shared by a/b/d and touches the crop box.
    axb.set_xscale("log"); axb.set_xlim(4, 1.2e8)
    axb.set_xticks([1e1, 1e3, 1e5, 1e7])
    axb.tick_params(axis="x", labelsize=8.8)
    axb.set_yticks(np.arange(len(v))[::-1])
    axb.set_yticklabels(lab, fontsize=7.4)          # right-aligned, tight against the axis
    axb.tick_params(axis="y", pad=2.5, length=0)
    axb.set_ylim(-0.62, len(v) - 0.38)
    axb.set_xlabel("Count (log scale)", labelpad=2.0)
    for i, (val, c) in enumerate(zip(v, col)):
        axb.text(val * 1.30, len(v) - 1 - i, f"{int(val):,}", va="center",
                 fontsize=7.4, color=c if c != GRY else "#535557")

    # ---- (d) the complete catalogue: eight predicates, five nested law sets
    # d gives up 0.24: panel e's height is protected by a test (the inset ticks must stay at
    # least 1 pt clear of the main panel's y=0 reference line), so nothing can be taken from e.
    # The row height therefore drops from 0.64 to 0.60 cm.
    HD = 6.88
    axd = fig.add_axes(_rect(EL, ER - EL, 8.86, HD))
    _rule_table(axd, cal, ER - EL, HD)

    # ---- (e) discovery trajectory over the unified programme index
    # the inset rectangle is pinned by two hard constraints: its top must stay below the main
    # panel's 0.70 plateau line, and its bottom plus one row of tick labels must stop above the
    # grey y = 0 reference line.
    # Keep the bottom edge fixed while making the panel 13% taller.  This
    # moves the main y=0 reference line clear of the inset's 1/8/16/24 labels.
    YE, HE = 16.49, 3.34
    axT = fig.add_axes(_rect(1.80, XRT - 1.80, YE, HE))
    _fig1_trajectory(axT, fig, _rect(6.20, 6.60, 17.62, 0.86))

    # e's y-axis decorations (a two-line axis title + tick labels) are aligned to EL: draw once
    # to measure the actual left edge, then shift the whole plot rectangle right by that
    # difference, so stamp() gives a/b/d/e the same letter x.
    fig.canvas.draw()
    rend = fig.canvas.get_renderer()
    dx = EL / _W - _ydeco_left(axT, fig, rend)
    bb = axT.get_position()
    axT.set_position([bb.x0 + dx, bb.y0, bb.width - dx, bb.height])

    # the b/c letters move down: the default position falls exactly on the top of a's funnel.
    # d's letter drops a further 0.37 cm: the table's header text starts 0.16 cm below the top
    # of the panel, so a letter positioned from the panel rectangle floats between c's axis
    # title and the header; moved down it sits against the first line of content in its own
    # panel, like b/c.
    DYBC, DYD = -0.012, -0.018
    stamp(fig, [(axe, "b", (0.0, DYBC)), (axb, "c", (0.0, DYBC)),
                (axd, "d", (0.0, DYD)), (axT, "e")])
    # a's panel rectangle starts at x=0 and is not in the same column as b/d/e, so stamp's
    # column logic does not apply to it; its letter is placed separately, still taking the same
    # x as the other panels.
    fig.text(EL / _W - 0.013, (_H - YA - 0.04) / _H, "a", fontsize=10,
             fontweight="bold", va="top", ha="left")
    save(fig, "fig1_agentic_law_learning")



# ─────────────────────────────────────────────────────────────────────────────
# Fig. 4 — Abstention-dominant failure of Pauling's rules
# ─────────────────────────────────────────────────────────────────────────────
SHORT = {"Pauling 2 (bond-strength dev.)": "Pauling 2",
         "Pauling 3 (edge/face sharing)": "Pauling 3",
         "Pauling 4 (high-valence contact)": "Pauling 4",
         "Pauling 5 (parsimony)": "Pauling 5",
         "This work: bl_min": r"$\rho$",
         "Volume per atom": "Volume/atom",
         "Shannon packing": "Shannon packing",
         "DFT E_hull (baseline)": "DFT energy"}
SLATE = "#29445C"
RSET = ["L1", "L1'", "L2", "L3", "L4"]
RLAB = {"L1": "Set 1", "L1'": "Set 1$'$", "L2": "Set 2", "L3": "Set 3",
        "L4": "Set 4"}
CMAP = {"Pauling 2": SLATE, "Pauling 3": SLATE, "Pauling 4": SLATE, "Pauling 5": SLATE,
        r"$\rho$": BLU, "Volume/atom": GRY, "Shannon packing": GRY,
        "DFT energy": GRN}


def fig4_validation():
    """Detection, blind spots and transfer: four panels."""
    _W, _H = 18.3, 14.90
    fig = plt.figure(figsize=(W2, _H * CM))

    def _rect(x0, w, ytop, h):
        return [x0 / _W, (_H - ytop - h) / _H, w / _W, h / _H]

    # the left column moves right and narrows: a's rightmost bar used to reach 7.96 cm, running
    # under b's row labels (which start at 7.71 cm) -- a's ink now stops at 7.43 cm. There used
    # to be a 1.5 cm blank band between the two rows; removing it gives the same total height to
    # taller panels.
    XL, XR_, XC1 = 1.75, 16.80, 5.90
    XB = 9.95
    HR = 5.60
    Y1, Y2 = 0.60, 8.30

# ---- (a) deployed validity filters against the whole ladder of law sets
    axa = fig.add_axes(_rect(XL, XC1, Y1, HR))
    v = pd.read_csv(DATA / "fig6_validity.csv").set_index("criterion")
    order = ["min pair distance > 0.5 A", "min pair distance > 0.7 A",
             "min pair distance > 1.0 A", "SMACT charge neutrality",
             "L1 (D1, tau=0.735)", "L1' (D1+D2)",
             "L2 (D1,D3-D5)", "L3 (D1,D3-D6)", "L4 (D1,D3-D8)"]
    lab = [r"$d$ 0.5$\,\AA$", r"$d$ 0.7$\,\AA$", r"$d$ 1.0$\,\AA$", "SMACT",
           "Set 1", "Set 1′", "Set 2", "Set 3", "Set 4"]
    c = [GRY, GRY, GRY, "#B3B8BD",
         BLU, PUR, ORA, RED, "#0A5A3C"]
    ex = [float(v.loc[k, "exclusion_total"]) for k in order]
    sa = [float(v.loc[k, "real_satisfaction"]) for k in order]
    axa.bar(range(len(order)), ex, color=c, width=0.60, lw=0, alpha=0.9)
    axa.set_xticks(range(len(order))); axa.set_xticklabels(lab, fontsize=7.4)
    for t in axa.get_xticklabels()[:4]:
        t.set_rotation(38); t.set_ha("right"); t.set_rotation_mode("anchor")
    axa.set_ylabel("Damage detection")
    axa.set_ylim(0, 1.20)
    axa.set_yticks([0, 0.2, 0.4, 0.6, 0.8, 1.0])
    axa.spines["left"].set_bounds(0, 1.0)
    for i, (e, s) in enumerate(zip(ex, sa)):
        axa.text(i, e + 0.017, f"{e:.3f}", ha="center", fontsize=7.0, color=c[i],
                 fontweight="bold")
        axa.text(i, 1.055, f"{s:.2f}", ha="center", fontsize=6.9, color="#97999C")
    axa.set_xlim(-0.62, 8.62)
    axa.text(-0.55, 1.135, "satisfaction of experimental structures", fontsize=7.4,
             color="#97999C", ha="left", va="center")
    axa.axvline(2.5, color="#B9BBBE", lw=0.7, ls=":", ymax=1.0 / 1.20)
    axa.axvline(3.5, color="#86888A", lw=0.8, ls=":", ymax=1.0 / 1.20)

    # ---- (b) per-perturbation-class exclusion, same test set
    axb = fig.add_axes(_rect(XB, XR_ - XB, Y1, HR))
    horder = ["min pair distance > 0.5 A", "min pair distance > 0.7 A",
              "min pair distance > 1.0 A", "SMACT charge neutrality",
              "L1 (D1, tau=0.735)",
              "D1 alone, tau=0.804", "L1' (D1+D2)", "L2 (D1,D3-D5)", "L3 (D1,D3-D6)",
              "L4 (D1,D3-D8)"]
    SC = [c2 for c2 in v.columns if c2.startswith("S") and c2[1].isdigit()]
    M = v.loc[horder, SC].values
    rows = [r"min $d$ > 0.5 $\AA$", r"min $d$ > 0.7 $\AA$", r"min $d$ > 1.0 $\AA$",
            "SMACT (composition)",
            # the set membership is in Fig. 1d; only the set names are kept here, or the full
            # Law/Set row labels would reach left into panel a's bars.
            "Set 1", "Law 1 only, " + r"$\tau$=0.804",
            "Set 1′", "Set 2", "Set 3", "Set 4"]
    im = axb.imshow(M, cmap="palmatrix", vmin=0, vmax=1, aspect="auto")
    axb.set_xticks(range(5))
    axb.set_xticklabels(CLASSLAB[:5], fontsize=7.0, linespacing=1.25)
    axb.set_yticks(range(len(rows))); axb.set_yticklabels(rows, fontsize=7.3)
    for i in range(len(rows)):
        for j in range(5):
            axb.text(j, i, f"{M[i, j]:.2f}", ha="center", va="center", fontsize=7.3,
                     color="w" if M[i, j] > 0.55 else "#212224")
    axb.axhline(2.5, color="k", lw=0.8)
    axb.axhline(3.5, color="k", lw=1.1)
    axb.add_patch(mp.Rectangle((2.5, 3.5), 1, 2, fill=False, ec="#101113", lw=1.3,
                               zorder=5))
    cax = fig.add_axes(_rect(XR_ + 0.16, 0.24, Y1, HR))
    cb = fig.colorbar(im, cax=cax)
    cb.set_label("Damage detection", fontsize=8.0); cb.ax.tick_params(labelsize=7.5)
    cb.outline.set_linewidth(0.5)
    for sp in axb.spines.values():
        sp.set_visible(True); sp.set_linewidth(0.5)

    # ---- (c) why the guard is needed
    axc = fig.add_axes(_rect(XL, XC1, Y2, HR))
    h = pd.read_csv(DATA / "fig4_rho_hist.csv")
    ctr = (h.lo + h.hi) / 2
    for col, cl, lb, al, zo in [
            ("real_ionic", SLATE, r"experimental, ionic ($f_i>$0.5)", 0.55, 3),
            ("real_nonionic", "#BDBFC2", r"experimental, non-ionic", 0.60, 2),
            ("S4", RED, "D4 expansion", 0.45, 4)]:
        axc.fill_between(ctr, h[col] / h[col].sum(), step="mid", color=cl, alpha=al,
                         lw=0, zorder=zo)
        axc.step(ctr, h[col] / h[col].sum(), where="mid", color=cl, lw=0.9, label=lb,
                 zorder=zo + 0.5)
    axc.axvline(1.05, color="k", lw=0.9, ls="--")
    axc.text(1.068, 0.180, r"$\rho$ = 1.05", fontsize=7.5, rotation=90, va="top")
    axc.set_xlim(0.45, 1.95); axc.set_ylim(0, 0.185)
    axc.set_xticks([0.5, 0.75, 1.0, 1.25, 1.5, 1.75])
    axc.set_yticks([0, 0.05, 0.10, 0.15])
    axc.set_xlabel(r"$\rho$"); axc.set_ylabel("Fraction of structures")
    # the legend moves outside the data area, matching panel d in the same row
    legc = axc.legend(frameon=False, fontsize=7.4, loc="lower left", ncol=2,
                      handlelength=1.2, labelspacing=0.30, columnspacing=1.2,
                      borderpad=0.1, bbox_to_anchor=(-0.02, 1.005))
    legc.get_texts()[0].set_fontsize(8.8)

    # ---- (d) leave-one-perturbation-out: certified search vs one inequality
    axd = fig.add_axes(_rect(XB, XR_ - XB, Y2, HR))
    lk = pd.read_csv(DATA / "fig3_loko.csv")
    x = np.arange(len(lk)); w = 0.20
    TREE, THR = "#8A8C8E", BLU        # matching Fig 2b: grey for the certified tree, blue for
                                      # the single rho threshold
    axd.bar(x - 1.5 * w, lk.tree_seen, w, color=TREE, lw=0, alpha=0.42)
    axd.bar(x - 0.5 * w, lk.tree_held, w, color=TREE, lw=0)
    axd.bar(x + 0.5 * w, lk.thr_seen, w, color=THR, lw=0, alpha=0.42)
    axd.bar(x + 1.5 * w, lk.thr_held, w, color=THR, lw=0)
    axd.set_xticks(x); axd.set_xticklabels([f"hold\n{dmglab(h2)}" for h2 in lk.held],
                                           fontsize=7.5)
    axd.set_ylabel("Damage detection")
    hs = [mp.Patch(fc=TREE, alpha=0.42, lw=0), mp.Patch(fc=TREE, lw=0),
          mp.Patch(fc=THR, alpha=0.42, lw=0), mp.Patch(fc=THR, lw=0)]
    axd.legend(hs, ["optimal tree, seen classes", "optimal tree, omitted class",
                    r"single $\rho$ threshold, seen",
                    r"single $\rho$ threshold, omitted class"],
               frameon=False, fontsize=7.4, loc="lower left", ncol=2,
               handlelength=1.4, labelspacing=0.30, columnspacing=1.2,
               borderpad=0.1, bbox_to_anchor=(-0.02, 1.005))
    axd.set_ylim(0, 1.02)
    axd.set_yticks([0, 0.2, 0.4, 0.6, 0.8, 1.0])

    # the c/d legends hang above their own axes; d's letter is raised further to clear c's
    # two-column legend.
    stamp(fig, [(axa, "a"), (axb, "b"),
                (axc, "c", (0.0, 0.30 / _H)), (axd, "d", (0.0, 0.55 / _H))])
    save(fig, "fig4_validation")


def wrap(s, n):
    out, line = [], ""
    for w in str(s).split():
        if len(line) + len(w) + 1 > n:
            out.append(line); line = w
        else:
            line = (line + " " + w).strip()
    if line:
        out.append(line)
    return "\n".join(out)


def figS8_ledger():
    r = pd.read_csv(DATA / "fig5_retractions.csv")
    # the layout works the figure height back from "row height = font size x leading": body text
    # at 8.2 pt with 1.38 leading -> 0.399 cm per row
    FS, LS, HH = 8.2, 1.38, 20.4
    LINE = FS * LS / 72 * 2.54 / HH           # fraction of the figure height one text line takes
    PAD = 0.23 / HH                           # clear space above and below each record
    fig, ax = plt.subplots(figsize=(W2, HH * CM))
    fig.subplots_adjust(left=0.0, right=1.0, top=1.0, bottom=0.0)
    ax.axis("off"); ax.set_xlim(0, 1); ax.set_ylim(0, 1)

    xs = [0.0, 0.037, 0.408, 0.700]
    hd = ["", "Claim that did not survive", "Why it looked true",
          "Diagnostic that exposed it"]
    ytop = 0.965
    for x, h in zip(xs, hd):
        ax.text(x, ytop, h, fontsize=9.0, fontweight="bold", va="top", color="#212224")
    ax.plot([0, 1], [ytop - 0.023] * 2, color="#323335", lw=0.9)

    y = ytop - 0.045
    for i, (_, row) in enumerate(r.iterrows()):
        a = wrap(row["claim"], 45)
        b = wrap(row["why_it_looked_true"], 35)
        c = wrap(row["what_exposed_it"], 36)
        nl = max(a.count("\n"), b.count("\n"), c.count("\n")) + 1
        h = LINE * nl + PAD
        if i % 2 == 0:
            ax.add_patch(mp.Rectangle((-0.004, y - h + 0.010), 1.008, h,
                                      fc="#F2F6F9", lw=0, zorder=0))
        ax.text(xs[0], y, f"R{i+1}", fontsize=FS, fontweight="bold", va="top",
                color=RED)
        ax.text(xs[1], y, a, fontsize=FS, va="top", color="#191A1C", linespacing=LS)
        ax.text(xs[2], y, b, fontsize=FS, va="top", color="#424446", linespacing=LS)
        ax.text(xs[3], y, c, fontsize=FS, va="top", color=GRN, linespacing=LS)
        y -= h
    ax.plot([0, 1], [y + 0.010] * 2, color="#323335", lw=0.9)
    save(fig, "figS8_refutation_ledger")


if __name__ == "__main__":
    # main Figs. 1, 2 and 4, plus the legacy asset figS8 (shown in the main text as
    # Supplementary Fig. S1, the refutation ledger).
    # fig4_abstention has been withdrawn from the manuscript (its content is folded into Fig. 5);
    # the generator is kept in the historical version under backup-20260817-figure-rename/ and
    # is no longer rerun by default.
    fig1(); fig2(); fig4_validation(); figS8_ledger()
